name: Deploy to Webuzo

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Next.js recommends 18 or 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy via SSH (Rsync)
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          REMOTE_PORT: ${{ secrets.PORT }}
          
          # what to upload
          SOURCE: ".next/"
          
          # where to upload
          TARGET: "/home/${{ secrets.USER }}/public_html/test.reviewsfactory.app/.next/"
          
          ARGS: "-rlgoDzvc -i"
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no"
